[org/xfce/mousepad/state/application]
session=['1;;+file:///home/marol/%D1%80%D0%BE%D0%B7%D0%BA%D0%BB%D0%B0%D0%B4%20%D1%81%D1%83%D0%B4%D0%BE%D0%B2%D0%B8%D1%85%20%D0%B7%D0%B0%D1%81%D1%96%D0%B4%D0%B0%D0%BD%D1%8C']

[org/xfce/mousepad/state/window]
width=754
height=1352
maximized=false
fullscreen=false

[org/xfce/mousepad/preferences/view]
color-scheme='oblivion'
font-name='JetBrainsMono Nerd Font Propo Medium 12'
use-default-monospace-font=false
word-wrap=true

[org/xfce/mousepad/state/search]
search-history=['Вихопень', 'Гамор', 'Лис', 'Дякун', 'Новацький', 'Недзеленко', 'Швачка', 'Тихий', 'Гнатів', 'Конончук', 'Коробов', 'Двернік', 'Михальчук Наталія Петрівна', '463/1918/26', 'opacity']
