[colors]
background      = #00000033
background-alt  = #285577
foreground      = #ebdbb2
foreground-alt  = #555
primary         = #285577
secondary       = #79740e
alert           = #bd2c40
aqua        = #8ec07c
beige        = #fbf1c7
black           = #282828
red             = #fb4934
orange          = #d65d0e
d-red        = #cc241d
d-orange    = #af3a03
b-green         = #689d6a
green           = #98971a
gray        = #a89984
l-yellow    = #fabd2f
yellow          = #d79921
blue            = #458588
magenta         = #b16286
cyan            = #076678
white           = #fbf1c7

[bar/example]
width = 100%
height = 20pt
radius = 0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 1pt
line-color = #f00 

border-size = 0
border-color = ${colors.black}

padding-left = 0
padding-right = 1

module-margin-left = 1
module-margin-right = 1

font-0 = JetBrains Mono Nerd Font:pixelsize=10;1
font-1 = unifont:fontformat=truetype:size=10:antialias=false;0
font-2 = siji:pixelsize=10;1
font-3 = Font Awesome 6 Free:style=Regular:pixelsize=10;2
font-4 = Font Awesome 6 Free:style=Solid:pixelsize=10;2

modules-left = xworkspaces 
modules-right = pulseaudio filesystem temperature memory cpu temperature-cpu wlan eth networkspeedup networkspeeddown date backlight battery xkeyboard

tray-position = right
tray-padding = 2

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[modules]

; [module/xwindow]
; type = internal/xwindow
; label = %title:0:30:...%

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

; wm-restack = generic
; wm-restack = bspwm
 wm-restack = i3

override-redirect = true

; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /
label-mounted =  %free%
label-mounted-foreground = ${colors.blue}
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.black}

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume>
; <bar-volume>
label-volume =  %percentage%%
label-volume-foreground = ${root.foreground}

label-muted =  
label-muted-foreground = ${colors.beige}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix =" "
format-prefix-foreground = ${colors.green}

label-layout = %layout%
label-layout-foreground = ${colors.green}

label-indicator-padding = 1
label-indicator-margin = 1

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = ""
format-prefix-foreground = ${colors.magenta}
# format-prefix-foreground = ${colors.foreground-alt}
# format-underline = #48f44f
label = %percentage:2%%
label-foreground = ${colors.magenta}

[module/temperature-cpu]
format-prefix= ""
type = internal/temperature
thermal-zone =
interval = 20
format = <label>
format-prefix-foreground = ${colors.orange}
hwmon-path = /sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon1/temp1_input
label = %temperature-c%
label-foreground = ${colors.orange}

;[module/temperature-gpu]
;type = internal/temperature
;thermal-zone =
;interval = 20
;format = <label>
;format-prefix-foreground = ${colors.red}
;hwmon-path = /sys/devices/pci0000:00/0000:00:03.1/0000:26:00.0/0000:27:00.0/0000:28:00.0/hwmon/hwmon3/temp2_input
;label = %temperature-c%
;label-foreground = ${colors.red}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.yellow}
# format-prefix-foreground = ${colors.foreground-alt}
# format-underline = #40a40a
label = %percentage_used%%
label-foreground = ${colors.yellow}

[module/wlan]
type = internal/network
interface = wlp3s0
interval = 3.0

format-connected = <ramp-signal> <label-connected>
label-connected =   
label-connected-foreground = ${colors.blue}

[module/mobile]
type = internal/network
interface = enp0s20f0u2
interval = 3.0

format-connected = <ramp-signal> <label-connected>
label-connected =   
label-connected-foreground = ${colors.blue}

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/eth]
type = internal/network
;interface = enp8s0
interval = 3.0

format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.l-yellow}
;label-connected = %local_ip%
;label-connected-foreground = ${colors.l-yellow}

format-disconnected-prefix = " "
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
label-disconnected = %ifname% disconnected
label-disconnected-foreground = ${colors.foreground-alt}

[module/networkspeedup]
type = internal/network
;interface = wlp3s0
interface = enp8s0
label-connected = "%upspeed:7%"
format-connected-prefix = ""
format-connected-foreground = ${colors.aqua}
;format-connected-background = ${colors.aqua}

[module/networkspeeddown]
type = internal/network
;interface = wlp3s0
interface = enp8s0
label-connected = "%downspeed:7%"
format-connected-prefix = ""
format-connected-foreground = ${colors.aqua}
;format-connected-background = ${colors.aqua}

[module/temperature]
type = internal/temperature
format-prefix= ""
thermal-zone = 0
warn-temperature = 60
format = <ramp> <label>

;format-underline = #f50a4d
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature-c%
label-warn = %temperature-c%
label-foreground = ${colors.red}
;label-warn-foreground = ${colors.d-red}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.red}

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
; Default: 100
full-at = 99

; format-low once this charge percentage is reached
; Default: 10
; New in version 3.6.0
low-at = 5

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = ADP1

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 5
; see "man date" for details on how to format the time string
; NOTE: if you want to use syntax tags here you need to use %%{...}
; Default: %H:%M:%S
time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <animation-charging> <label-charging>

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging = <ramp-capacity> <label-discharging>

; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
;format-full = <ramp-capacity> <label-full>

; Format used when battery level drops to low-at
; If not defined, format-discharging is used instead.
; Available tags:
;   <label-low>
;   <animation-low>
;   <bar-capacity>
;   <ramp-capacity>
; New in version 3.6.0
;format-low = <label-low> <animation-low>

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging =  %time% %percentage%%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = %time%  %percentage%%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
label-full = 

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
; New in version 3.6.0
label-low = 

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

; Only applies if <bar-capacity> is used
bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
; Framerate in milliseconds
animation-charging-framerate = 750

; Only applies if <animation-discharging> is used
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
; Framerate in milliseconds
animation-discharging-framerate = 500

; Only applies if <animation-low> is used
; New in version 3.6.0
animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200

[global/wm]
margin-top = 5
margin-bottom = 5

[module/date]
type = internal/date
interval = 5

date =
date-alt = " %Y-%m-%d"

time = %H:%M
time-alt = %H:%M:%S
;format-prefix-foreground = ${colors.foreground-alt}
label = %date% %time%
label-foreground = ${colors.b-green}

[module/backlight]
type = internal/backlight

; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
; Default: first usable card in /sys/class/backlight (new in version 3.7.0)
card = intel_backlight

; Use the `/sys/class/backlight/.../actual-brightness` file
; rather than the regular `brightness` file.
; New in version 3.6.0
; Changed in version: 3.7.0: Defaults to true also on amdgpu backlights
; Default: true
use-actual-brightness = true

; Interval in seconds after which after which the current brightness is read
; (even if no update is detected).
; Use this as a fallback if brightness updates are not registering in polybar
; (which happens if the use-actual-brightness is false).
; There is no guarantee on the precisio of this timing.
; Set to 0 to turn off
; New in version 3.7.0
; Default: 0 (5 if use-actual-brightness is false)
poll-interval = 0

; Enable changing the backlight with the scroll wheel
; NOTE: This may require additional configuration on some systems. Polybar will
; write to `/sys/class/backlight/${self.card}/brightness` which requires polybar
; to have write access to that file.
; DO NOT RUN POLYBAR AS ROOT. 
; The recommended way is to add the user to the
; `video` group and give that group write-privileges for the `brightness` file.
; See the ArchWiki for more information:
; https://wiki.archlinux.org/index.php/Backlight#ACPI
; Default: false
enable-scroll = true

; Interval for changing the brightness (in percentage points).
; New in version 3.7.0
; Default: 5
scroll-interval = 10

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini

